language: java
jdk: openjdk8
sudo: false
cache:
  directories:
    - $HOME/.m2
script:
  - mvn clean install
  - mvn -DrepoToken=$COVERALLSTOKEN jacoco:report coveralls:report

notifications:
  email:
    on_success: never
    on_failure: never
